au.yaml
Added 'Friday before the AFL Grand Final' holiday for 2018:
http://www.business.vic.gov.au/victorian-public-holidays-and-daylight-saving/victorian-public-holidays
=> Add AFL holiday

au.yaml
Still PFC-1691 fixing definitions for xmas and ANZAC day for 2020/2021 while we're here
=> [PFC-1691] (fix) Add definitions for additional recognised public holidays

au.yaml
Discrepancy between FWO and NT Gov website in regard to Boxing Day 26/12 being regarded as public holiday.
On the NT Gov website both Boxing Day 26/12 and 28/12 are regarded as public holiday. I called up the NT Gov office and it has been confirmed that both days are considered public holidays and employees should get public holiday rates on both days worked. 
FWO are aware of the discrepancy and have advised me to follow NT Gov. They will still get back to me about the relevant changes. 
Applies to **Christmas & Boxing Day**
=> [PFC-1440] (fix) Adding NT Additional Public Holiday Changes for 2020/21

us.yaml
the test_background_sync_job_test is failing when trying to merge payaus change for removing melbourne holiday
changed the 2021, 2022, and 2027 test for USA christmas day
=> fixed USA holiday tests

au.yaml, us.yaml
Reverts TandaHQ/definitions#22
=> Revert "removed Melbourne Cup holiday from au_vic region and fixed a few tests"

au.yaml
Have changed a few things:
NT: The additional Christmas day will fall on Monday if on Sunday (instead of Tuesday)
SA: Christmas day is substituted if it falls on a Saturday
NSW, VIC, ACT, WA, NT, QLD: New year’s day will always fall on 1st Jan, with additional holiday added on the next Monday if it falls on a weekend.
NT: Boxing day is substituted to Tuesday if it falls on Sunday or Monday, and moves to Monday if on Saturday
SA: Boxing day is substituted to Tuesday if it falls on Monday
SA: There is no additional Christmas public holiday if it falls on a Saturday
=> Pfc 3593/au nyd and christmas changes

nz.yaml
Added Matariki Public Holiday. Link to government website [here](https://www.mbie.govt.nz/assets/matariki-dates-2022-to-2052-matariki-advisory-group.pdf).
- There was no way of writing a method for these days so they were hard coded into the file.
=> Add Matariki manual logic

nz2_calendar_dates.yaml
Added Matariki Public Holiday. Link to government website [here](https://www.mbie.govt.nz/assets/matariki-dates-2022-to-2052-matariki-advisory-group.pdf).
There was no way of writing a method for these days so they were hard coded into the file.
This is for the second NZ yaml file. Domino's NZ use both the Monday-ised and normal PH's. So copying the cody from the other NZ yaml file.
=> PFC-4385 (fix) Matariki PH to the second nz yaml

au.yaml
Vic AFL Grand Final Public Holiday is hard coded. So I added 2022 with this PR.
=> PFC-4532 (fix) 2022 AFL Grand Final VIC

au.yaml
Adding the public holiday for all the states and territories in Australia for the 'Day of mourning for Queen Elizabeth II' on the 22nd of September 2022.
Amended the yaml.
This PR is part of three. **Definitions** > Holidays > Payaus
=> PFC-4672 (fix) Mourning for Queen Elizabeth II (au only)

au.yaml, nz.yaml, nz2_calendar_dates.yaml
Adding the public holiday for both the NZ pubic holidays pushed to Monday and the others for the 'Day of mourning for Queen Elizabeth II' on the 26th of September 2022.
Amended the yaml. I also fixed the Aus one to not refer to week and day but just `mday:22`
This PR is part of three. **Definitions** > Holidays > Payaus
=> PFC-4676 (fix) Mourning for Queen Elizabeth II (nz only)

gb.yaml
We have decided that at this short notice, it is safer to not add this bank holiday to the gem, and will handle this manually. 
https://tandadocs.atlassian.net/browse/ISD-12423
=> ISD-12423 - Remove new BH for UK

nf.yaml
Link to [PFC-4905 here](https://tandadocs.atlassian.net/browse/PFC-4905).
This PR is to add public holidays to the the Norfolk Island list.
2022 dates:
2023 dates:
Each new day calls the `observed: to_monday_if_weekend(date)` meaning that if this public holiday falls on the weekend they'll get an extra day. Otherwise this method will give us nil so it will never double up if the public holiday is on a weekday.
Made a special function for the observed Christmas day to jump from sunday to tuesday. Only applies when Christmas falls on Sunday.
Will get all three repo's in sync so will test on the dev server in Payaus repo.
=> PFC-4905 (fix) Additional days for Norfolk Island

SYNTAX.md, au.yaml
Link to [PFC-4946 here](https://tandadocs.atlassian.net/browse/PFC-4946).
Adding the public holiday for SA to have both the day of and the observed day for New Years. 
Confirmation of these days can be found on the Fairwork Australia website here: https://www.fairwork.gov.au/employment-conditions/public-holidays/2023-public-holidays#SA
Usual update process for Public Holidays. This PR is part of three. Definitions > Holidays > **Payaus**.
Ran a `bundle exec tapioca gem holidays` after updating the gem files. First commit is for testing, second will be after the Definitions and Holidays repo's have merged PR's.
The logic for this day and the observed day is used for nearly every other state. So I've just removed SA from the method that only gives them the observed day on a weekday.
---
=> PFC-4946 (fix) SA to get New Years day and observed 

ie.yaml
Add St Brigids day as Irish Bank Holiday
https://tandadocs.atlassian.net/browse/L2S-111
=> L2S-111 - Add St Brigids Day as Irish Bank holiday

es.yaml
Removing 1st of Jan from ES public holidays as of 2023
https://tandadocs.atlassian.net/browse/L2S-2153
=> L2S-2153 - Remove 1st of Jan from ES PH

my.yaml
Ticket: https://tandadocs.atlassian.net/browse/PFC-4972
Corrected public holiday for Malaysia to fall on the first Monday of June
=> (Hotfix) (PFC-4972) Correct public holiday for Malaysia to be first Monday of June

cy.yaml, index.yaml
https://tandadocs.atlassian.net/browse/UKSUP-316
Ref:
Note: In the other reference docs you can see that many bank holidays are not stationary, but move around as a set amount of days before/after the annual Orthodox date, these are account for in these function modifers which notify how many days after/before the orthodox date they are:
Other Notes:
https://docs.google.com/document/d/17L-_4xeZQs4vamHGCDgKd60DOLX0msM7xBNr1aj0jKI/edit
=> UKSUP-316 - Add Cyprus Bank Holidays to Definitions and Edit Incorrect Greece BH

au.yaml
I quite literally added the incorrect keyword for checking when the holiday was meant to start from.
=> hotfix: update a keyword to be correct

dk.yaml, no.yaml
Palmesøndag is no longer a holiday so yeeting it
=> Remove Palmesøndag from denmark and norway
