TandaHQ/definitions

us.yaml

Check each commit independently.

3 US holiday issues

---

au.yaml

[PFC-1691] (fix) Add Additional Boxing Day Holiday
RE: https://github.com/TandaHQ/payaus/pull/11110
Manually adding additional boxing day public holiday definitions for AU for applicable states (VIC, ACT, NSW, QLD and WA)

[PFC-1691] (fix) Add Additional Boxing Day Holiday

---

au.yaml

[PFC-1691] (fix) Add main country code :au back to ANZAC day

[PFC-1691] (fix) Add main country code :au back to ANZAC day

---

au.yaml

Changes implemented in https://github.com/TandaHQ/payaus/pull/11265

Fix Airbrake Unexpected Return Error Inside Lambda

---

gb.yaml

Accidentally merged to master, reverting to last merged branch to fix git history

Revert to e5d5ca2

---

gb.yaml

Change May Day in the UK to the correct date

Update May Day in UK

---

mu.yaml

adding Mauritius holidays to settings

feature / Create mu.yaml

---

au.yaml
mu.yaml

Updates syntax. to `mu.yaml` introduced in https://github.com/TandaHQ/definitions/pull/18

hotfix/ mu yaml syntax

---

au.yaml

[Jira](https://tandadocs.atlassian.net/browse/PFC-3068)
https://www.timeanddate.com/holidays/australia/picnic-day

Add picnic day to nt

---

us.yaml

Reverts TandaHQ/definitions#23

Revert "fixed USA holiday tests"

---

gb.yaml

Added Capitalisation for Jubilee Bank Holiday and Early May Bank Holiday

PFC-3613 (bug fix) Update holiday gem reference for GB holiday date changes- Capitalise Bank Holidays

---

au.yaml

nt now has additional public holiday for boxing day

nt now has additional public holiday for boxing day

---

gb.yaml

https://tandadocs.atlassian.net/browse/ISD-12423
Updates gem to add new bank holiday for UK for Queens death

ISD-12423 - Add new Bank hol for UK

---

mu.yaml

https://tandadocs.atlassian.net/browse/ISD-12670

ISD-12670 - Update diwali date in mu.yaml

---

es.yaml

Use correct date range for spanish bank holiday

Change year range for es bh

---

gb.yaml

https://tandadocs.atlassian.net/browse/L2S-113
Add King Coronation as a once off BH for 2023.

L2S-113 - Add Kings Coronation to UK BH 2023

---

index.yaml

@beau added Uruguayan holidays but forgot to update the index file. This adds that update

add uruguay to index file

---

au.yaml

Link to [PFC-5173 here](https://tandadocs.atlassian.net/browse/PFC-5174)
NT finally get Easter Sunday as a public holiday.
Added tests and made it so this public holiday only applies from 2023 and into the future.
Nil
Run tests in the holidays repo. Shows in the prebuild holidays.
---
!no-server
[♻️ Recreate MS](https://tandadocs.atlassian.net/wiki/spaces/DEV/pages/1386905601/Recreate+a+Multi-Staging+Branch) | [🐞 Debugging MS](https://tandadocs.atlassian.net/wiki/spaces/DEV/pages/414089232/Debug+MS+issues+in+AWS) | [🦾 MS Commands](https://github.com/TandaHQ/payaus/tree/master/config/deploy/multi-staging#how-to-use-ms) | [⛹️ Skills Matrix](https://docs.google.com/spreadsheets/d/13dTaNgxvT1Bj7H-5-B-j8xU_9Y5EQE9nn6j4kYRep5A/edit#gid=0) | [💯 Code Review …

PFC-5173 (fix) Easter Sunday for NT

---

nf.yaml

Adding as a test for presentation - will revert in another PR

Change Capitalization for NF comment

---

au.yaml

Description of changes
Link to [L2S-2720 here](https://tandadocs.atlassian.net/browse/L2S-2720)
Added king's birthday from 2023 onwards for all states of Australia

added king's bday

---

mu.yaml

First time getting involved and I had no idea I had permissions to merge directly into master 🙃 removing the changes here

remove-force-changes

---

mu.yaml

https://tandadocs.atlassian.net/browse/L2S-3481
We have found there were some public holidays missing for MU, and some changes dates for each year so also adding them.

L2S-3481 - Fix MU Public Holidays

---

au.yaml

https://tandadocs.atlassian.net/browse/L2S-3549
- Updated King's birthday information for Western Australia

Hotfix: Updated kings birthday

---

au.yaml

Ticket: https://tandadocs.atlassian.net/browse/L2S-3549
- The date for this year was incorrect, I've created an exception for it so that it displays the correct date

Hotfix: created a 2024 exception

---

au.yaml

- With the last PR I made, I accidentally changed the indentation of a test and added a line space that broke the rake generate command.

hotfix: Removed a troublesome space

---

au.yaml

Fixed broken syntax from .yaml file for ease of use.

L2S-3549 - King's birthday 2024 exception update

---

sg.yaml

Added singapore holidays to definitions
There are some annoying holidays that change every year, so ive added as far into the future for these holidays as i could

Feature | add Singapore holidays

---

au.yaml

Ticket: https://tandadocs.atlassian.net/browse/L2S-3570
- Adding Easter Sunday public holiday for South Australia to the list

Add Easter Sunday Holiday 

---

ie.yaml

As per BOH
https://tandadocs.atlassian.net/browse/L2S-3600

Update St Brigid's Day for 2025
